### ISSUE TITLE
Investigate rabbitmq memory issues

### ISSUE THREAD

**Issue by steersbob** [BrewBlox/brewblox-ctl-lib#12]

**Comment by j616** [comment]
Just hit against this for the 3rd time. Could this be bumped up in priority?

**Comment by steersbob** [comment]
Our office fridge hasn't reproduced the issue yet, so I'll probably have to increase the system load.

- Which model Pi and Spark controller are you using?
- How many Spark controllers / services are you using?
- How many blocks are active on your Spark controller? (ballpark estimate is fine)

**Comment by j616** [comment]
I think it's the old Model B 3 (not the + iirc). My spark is the not the most recent, the one before that. The one with the chunkier case. 

I'm only using one spark. 

I've got around 40 blocks active on it (one full fermentation fridge config and another fridge without the fermentor parts).
