### ISSUE TITLE
IPv6 / connectivity issues

### ISSUE THREAD

**Issue by steersbob** [BrewBlox/brewblox-ctl-lib#183]
https://medium.com/@skleeschulte/how-to-enable-ipv6-for-docker-containers-on-ubuntu-18-04-c68394a219a2

https://www.cyberciti.biz/faq/linux-show-dropped-packets-per-interface-command/

https://stackoverflow.com/questions/59787464/docker-swarm-restart-all-containers-on-host-periodically

https://github.com/systemd/systemd/issues/3374

https://github.com/moby/libnetwork/pull/2380

https://docs.docker.com/config/daemon/ipv6/

https://github.com/moby/moby/issues/38203

 sudo sed -i "/net.ipv6.*.disable_ipv6 = 1/d" /etc/sysctl.conf

https://github.com/docker/for-linux/issues/914

**Comment by jpaarhuis** [comment]
Hey @steersbob, I see you linked to https://github.com/moby/moby/issues/38203. I'm facing this exact same issue. Is ipv6 the solution to avoid service restarts on the node?

**Comment by jpaarhuis** [comment]
Nvm, found a potential solution here, might help you as well. https://github.com/moby/moby/issues/36311

**Comment by steersbob** [comment]
@jpaarhuis Probably. We can reproduce the problem, and the problem goes away when IPv6 is enabled per https://docs.docker.com/config/daemon/ipv6/. This doesn't mean I can confidently say I understand the issue and its solution.

Edit: to be explicit, we are running a docker-compose environment - not swarm.

**Comment by jpaarhuis** [comment]
Ok, we do run swarm and it seems like a specific issue to swarm. We're trying out this solution now: https://github.com/moby/moby/issues/36311.

**Comment by steersbob** [comment]
Editing the docker daemon config seems to consistently fix the issue on all supported platforms. Closing this issue now.
